bookStoreTurkcell/Controllers/AuthorsController.cs
using bookStoreTurkcell.Models;
using bookStoreTurkcell.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookStoreTurkcell.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AuthorsController : Controller
    {
        private IAuthorService authorService;
        private IBookService bookService;

        public AuthorsController(IAuthorService authorService, IBookService bookService)
        {
            this.authorService = authorService;
            this.bookService = bookService;
        }
        public IActionResult Index()
        {
            var authors = authorService.GetAuthors(); //List authors
            return View(authors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Author author)
        {

            if (authorService.DoesAuthorExist(author))
            {
                ViewBag.Message = 0;
                return View(author);

            }
            else if (ModelState.IsValid) //If there are no errors; add the author and return to the list
            {
                authorService.AddAuthor(author); 
                return RedirectToAction(nameof(Index));
            }
            
            return View(); //If there is an error open the same view again
        }


        public IActionResult Edit(int authorID)
        {
            var author = authorService.GetAuthorByID(authorID);

            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        [HttpPost]
        public IActionResult Edit(Author author)
        {
            if (ModelState.IsValid)
            {

                authorService.UpdateAuthor(author);
                return RedirectToAction(nameof(Index));
            }

            return View(author);
        }

        public IActionResult Delete(int authorID)
        {
            var author = authorService.GetAuthorByID(authorID);

            if (author == null)
            {
                return NotFound();
            }
            
            return View(author);
        }

        [HttpPost]
        public IActionResult Delete(Author author)
        {
            if (authorService.authorBook(author.ID))
            {
                ViewBag.Message = 0;
                return View(author);
            }
            
            authorService.DeleteAuthor(author);
            return RedirectToAction(nameof(Index));

        }

    

        public IActionResult Details(int authorID)
        {
            var author = authorService.GetAuthorByID(authorID);

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }


    }
}

bookStoreTurkcell/Controllers/BooksController.cs
using bookStoreTurkcell.Models;
using bookStoreTurkcell.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookStoreTurkcell.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BooksController : Controller
    {
        private IBookService bookService;
        private IGenreService genreService;
        private IAuthorService authorService;
        private IPublisherService publisherService;

        public BooksController(IBookService bookService, IGenreService genreService, IAuthorService authorService, IPublisherService publisherService)
        {
            this.bookService = bookService;
            this.genreService = genreService;
            this.authorService = authorService;
            this.publisherService = publisherService;
        }
        public IActionResult Index()
        {
            var books = bookService.GetBooks(); //List books
            return View(books);
        
        }

        public IActionResult Create()
        {
            //We want to show genres, authors and publisher as dropdown menus
            //In order to do that we need to show their names to the user but keep their ID's for recognition
            //We also need them to be IEnumerable SelectListItem for asp-item to show them
            //To reach them easily we turn these processes into new methods
            
            List<SelectListItem> selectListGenres = getGenresToSelect();
            ViewBag.GenreItems = selectListGenres;

            List<SelectListItem> selectListAuthors = getAuthorsToSelect();
            ViewBag.AuthorItems = selectListAuthors;
            
            List<SelectListItem> selectListItems = getPublisherToSelect();
            ViewBag.PubItems = selectListItems;

            return View();
        }

        private List<SelectListItem> getPublisherToSelect()
        {
            var pubList = publisherService.GetPublishers();
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            pubList.ToList().ForEach(p => selectListItems.Add(new SelectListItem
            {
                Text = p.Name,
                Value = p.ID.ToString()
            }));
            return selectListItems;
        }

        private List<SelectListItem> getAuthorsToSelect()
        {
            var authorList = authorService.GetAuthors();
            List<SelectListItem> selectListAuthors = new List<SelectListItem>();
            authorList.ToList().ForEach(a => selectListAuthors.Add(new SelectListItem
            {
                Text = a.Name,
                Value = a.ID.ToString()
            }));
            return selectListAuthors;
        }

        private List<SelectListItem> getGenresToSelect()
        {
            var genreList = genreService.GetGenres();
            List<SelectListItem> selectListGenres = new List<SelectListItem>();
            genreList.ToList().ForEach(g => selectListGenres.Add(new SelectListItem
            {
                Text = g.Name,
                Value = g.ID.ToString()
            }));
            return selectListGenres;
        }

        [HttpPost]
        public IActionResult Create(Book book)
        {
            if (bookService.DoesBookExist(book))
            {
                ViewBag.Message = 0;
                return View();

            }
            else if (ModelState.IsValid) //If there are no errors; add the book and return to the list
            {
                bookService.AddBook(book);
                return RedirectToAction(nameof(Index));
            }
            
            List<SelectListItem> selectListGenres = getGenresToSelect();
            ViewBag.GenreItems = selectListGenres;

            List<SelectListItem> selectListAuthors = getAuthorsToSelect();
            ViewBag.AuthorItems = selectListAuthors;

            List<SelectListItem> selectListItems = getPublisherToSelect();
            ViewBag.PubItems = selectListItems;

            return View(); //If there is an error open the same view again, also show the dropdown items again
        }

        public IActionResult Edit(int bookID)
        {
            var book = bookService.GetBookDetailsByID(bookID);
           
            if (book == null)
            {
                return NotFound();
            }

            List<SelectListItem> selectListGenres = getGenresToSelect();
            ViewBag.GenreItems = selectListGenres;

            List<SelectListItem> selectListAuthors = getAuthorsToSelect();
            ViewBag.AuthorItems = selectListAuthors;

            List<SelectListItem> selectListItems = getPublisherToSelect();
            ViewBag.PubItems = selectListItems;

            return View(book);
        }

        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
              
                int editedRowsCount = bookService.UpdateBook(book);
                return RedirectToAction(nameof(Index));
            }

            List<SelectListItem> selectListGenres = getGenresToSelect();
            ViewBag.GenreItems = selectListGenres;

            List<SelectListItem> selectListAuthors = getAuthorsToSelect();
            ViewBag.AuthorItems = selectListAuthors;

            List<SelectListItem> selectListItems = getPublisherToSelect();
            ViewBag.PubItems = selectListItems;

            return View(book);
        }

        public IActionResult Delete(int bookID)
        {
            var book = bookService.GetBookDetailsByID(bookID);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpPost]
        public IActionResult Delete(Book book)
        {
           
                bookService.DeleteBook(book);
                return RedirectToAction(nameof(Index));
            
        }


        public IActionResult Details(int bookID)
        {
            var book = bookService.GetBookDetailsByID(bookID);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

    }
}

bookStoreTurkcell/Controllers/CartController.cs
using bookStoreTurkcell.Models;
using bookStoreTurkcell.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookStoreTurkcell.Controllers
{
    public class CartController : Controller
    {
        private IBookService bookService;

        public CartController(IBookService bookService)
        {
            this.bookService = bookService;
        }
        public IActionResult Index(string returnURL)
        {
            var cart = GetCart();
            ViewBag.ReturnURL = returnURL;
            return View(cart);
        }

        [HttpPost]
        public IActionResult AddToCart(int bookID, string returnURL)
        {
            var selectedBook = bookService.GetBookByID(bookID);
            if (selectedBook == null)
            {
                return NotFound();
            }

            Cart cart = GetCart() ?? new Cart();
            cart.AddItem(selectedBook, 1);
            SaveCart(cart);

            return RedirectToAction(nameof(Index), nameof(Cart), new { returnURL = returnURL});
        }

        Cart GetCart()
        {
            var data = HttpContext.Session.GetString("My Cart");
            if (data == null)
            {
                return null;
            }
            else
            {
               return JsonConvert.DeserializeObject<Cart>(data);
            }
        }

        void SaveCart(Cart cart)
        {
            HttpContext.Session.SetString("My Cart", JsonConvert.SerializeObject(cart));
        }

        public IActionResult Delete(int ID)
        {
            var cart = GetCart(); 
            var deleteBook = bookService.GetBookByID(ID);
            cart.Remove(deleteBook);
            SaveCart(cart);

            return RedirectToAction(nameof(Index), nameof(Cart));
        }

    }
}

bookStoreTurkcell/Controllers/GenresController.cs
using bookStoreTurkcell.Models;
using bookStoreTurkcell.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookStoreTurkcell.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GenresController : Controller
    {
        private IGenreService genreService;

        public GenresController(IGenreService genreService)
        {
            this.genreService = genreService;
        }
        public IActionResult Index()
        {
            var genres = genreService.GetGenres(); //List the genres
            return View(genres);
        }

        public IActionResult Create()
        {
            return View();       
        }

        [HttpPost]
        public IActionResult Create(Genre genre)
        {
            if (genreService.DoesGenreExist(genre))
            {
                ViewBag.Message = 0;
                return View();
            }
            else if (ModelState.IsValid) //If there are no errors; add the genre and return to the list
            {
                genreService.AddGenre(genre);
                return RedirectToAction(nameof(Index));
            }

            return View(); //If there is an error open the same view again
        }

        public IActionResult Edit(int genreID)
        {
            var genre = genreService.GetGenreByID(genreID);

            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        [HttpPost]
        public IActionResult Edit(Genre genre)
        {
            if (ModelState.IsValid)
            {

                genreService.UpdateGenre(genre);
                return RedirectToAction(nameof(Index));
            }

            return View(genre);
        }

        public IActionResult Delete(int genreID)
        {
            var genre = genreService.GetGenreByID(genreID);

            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        [HttpPost]
        public IActionResult Delete(Genre genre)
        {
            if (genreService.genreBook(genre.ID))
            {
                ViewBag.Message = 0;
                return View(genre);
            }

            genreService.DeleteGenre(genre);
            return RedirectToAction(nameof(Index));

        }
    }
}

bookStoreTurkcell/Views/Shared/_AuthorCard.cshtml
@model Author
@{  
    var request = ViewContext.HttpContext.Request;
    string returnURLValue = request.QueryString.HasValue ?
    $"{request.Path}{request.QueryString}" : request.Path.ToString();

}
    <div class="card h-100 text-white bg-secondary mb-3">
        <img src="@Model.ImageUrl" class="card-img-top img-thumbnail " alt="Yazar">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <h6 class="card-text">@Model.Bio</h6>
            <form method="post">
                <input type="hidden" name="returnURL" value="@returnURLValue" />
                <button type="submit" class="btn btn-light">Detaylar</button>
            </form>

        </div>
    </div>

bookStoreTurkcell/Views/Shared/_BookCard.cshtml
@model Book
@{ 
    var request = ViewContext.HttpContext.Request;
    string returnURLValue = request.QueryString.HasValue ?
        $"{request.Path}{request.QueryString}" : request.Path.ToString();

}
<div class="card h-100 text-white bg-secondary mb-3">
    <img src="@Model.ImageUrl" class="card-img-top img-thumbnail " alt="Kitap">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <h6 class="card-text">@Model.Author.Name</h6>
        <h6 class="card-text">@Model.Publisher.Name</h6>
        <p class="card-text"><s>@Model.Price</s> yerine <strong>@(Model.Price * (decimal)(1-Model.Discount))</strong></p>
        <form asp-action="AddToCart" asp-controller="Cart" asp-route-bookID="@Model.ID" method="post">
            <input type="hidden" name="returnURL" value="@returnURLValue"/>
            <button type="submit" class="btn btn-warning">Sepete Ekle</button>
        </form>

    </div>
</div>

bookStoreTurkcell/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BegumBooks </title>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img img src="https://lh3.googleusercontent.com/eRPGOfo-dToceuOoVpwhWsSlGuot04AbCwz4hOPsslvPGrr5GXD_Q0TQo_x32o72FFwMXe5kTxAT-6qM5o83loPHt_WqLrSdYVWS5Hp8Eb0II8cPJ_cowgdDO1TXVgYKl5-Pui4izQ=w2400" alt="" width="100" height="100" class="d-inline-block align-top">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <div class="container">
                            <div class="row">
                                <div class="col-5">
                                    <li class="nav-item">
                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            @if (User.IsInRole("Admin"))
                                            {

                                                <div class="dropdown">
                                                    <button class="btn btn-warning dropdown-toggle" type="button" data-toggle="dropdown">
                                                        Hoşgeldin @User.Identity.Name, neler yapacaksın?
                                                        <span class="caret"></span>
                                                    </button>
                                                    <ul class="dropdown-menu">
                                                        <li><a class="dropdown-item" asp-controller="Account" asp-action="Logout">Çıkış Yap</a></li>
                                                        <div class="dropdown-divider"></div>
                                                        <li><a class="dropdown-item" asp-controller="Books" asp-action="Index">Kitap İşlemleri</a></li>
                                                        <li><a class="dropdown-item" asp-controller="Authors" asp-action="Index">Yazar İşlemleri</a></li>
                                                        <li><a class="dropdown-item" asp-controller="Publishers" asp-action="Index">Yayınevi İşlemleri</a></li>
                                                        <li><a class="dropdown-item" asp-controller="Genres" asp-action="Index">Tür İşlemleri</a></li>
                                                    </ul>
                                                </div>
                                            }
                                            else if (User.IsInRole("Standard User"))
                                            {
                                                <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Logout">
                                                    Merhaba @User.Identity.Name :) <strong> (Çıkış Yap)</strong>
                                                </a>

                                            }

                                        }

                                        else
                                        {
                                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Login">
                                                Giriş Yap
                                            </a>
                                        }
                                    </li>
                                </div>
                                <div class="col">
                                    <li class="nav-item">
                                        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="Author">
                                            Yazarlar
                                        </a>
                                    </li>
                                </div>
                                <div class="col">
                                    <li class="nav-item">
                                        <a class="btn btn-light" asp-area="" asp-controller="Home" asp-action="Publisher">
                                            Yayınevleri
                                        </a>
                                    </li>
                                </div>
                                <div class="col">
                                    <li class="nav-item ">
                                        <a class="btn btn-info" asp-area="" asp-controller="Cart" asp-action="Index">
                                            Sepetim
                                        </a>
                                    </li>
                                </div>
                                    </div>           
                            </div>
                        </div>
                    </ul>
                  
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div class="row">
                <div class="col-3">@await Component.InvokeAsync("Menu")</div>
                <div class="col-9"> @RenderBody()</div>
            </div>
           
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - bookStoreTurkcell - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>