bookStoreTurkcell/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookStoreTurkcell.Models
{
    public class Cart
    {
        private List<CartLine> cartLines = new List<CartLine>();
        public void AddItem(Book book, int quantity)
        {
            var existingLine = cartLines.FirstOrDefault(b => b.Book.ID == book.ID);
            if (existingLine == null)
            {
                cartLines.Add(new CartLine { Book = book, Quantity = quantity });
            }
            else
            {
                existingLine.Quantity += quantity;
            }
        }

        public void Remove(Book book) => cartLines.RemoveAll(c => c.Book.ID == book.ID);

        public void Clear() => cartLines.Clear();

        public decimal GetTotalValue() => cartLines.Sum(s => (s.Book.Price*(decimal)(1 - s.Book.Discount)) * s.Quantity);

        public IEnumerable<CartLine> CartLines => cartLines;



    }
}

bookStoreTurkcell/Controllers/CartController.cs
using bookStoreTurkcell.Models;
using bookStoreTurkcell.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookStoreTurkcell.Controllers
{
    public class CartController : Controller
    {
        private IBookService bookService;

        public CartController(IBookService bookService)
        {
            this.bookService = bookService;
        }
        public IActionResult Index(string returnURL)
        {
            var cart = GetCart();
            ViewBag.ReturnURL = returnURL;
            return View(cart);
        }

        [HttpPost]
        public IActionResult AddToCart(int bookID, string returnURL)
        {
            var selectedBook = bookService.GetBookByID(bookID);
            if (selectedBook == null)
            {
                return NotFound();
            }

            Cart cart = GetCart() ?? new Cart();
            cart.AddItem(selectedBook, 1);
            SaveCart(cart);

            return RedirectToAction(nameof(Index), nameof(Cart), new { returnURL = returnURL});
        }

        Cart GetCart()
        {
            var data = HttpContext.Session.GetString("My Cart");
            if (data == null)
            {
                return null;
            }
            else
            {
               return JsonConvert.DeserializeObject<Cart>(data);
            }
        }

        void SaveCart(Cart cart)
        {
            HttpContext.Session.SetString("My Cart", JsonConvert.SerializeObject(cart));
        }

        public IActionResult Delete(int ID)
        {
            var cart = GetCart(); 
            var deleteBook = bookService.GetBookByID(ID);
            cart.Remove(deleteBook);
            SaveCart(cart);

            return RedirectToAction(nameof(Index), nameof(Cart));
        }

    }
}

bookStoreTurkcell/Controllers/OrderController.cs
using bookStoreTurkcell.Models;
using bookStoreTurkcell.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace bookStoreTurkcell.Controllers
{
    public class OrderController : Controller
    {
        private IUserService userService;
 

        public OrderController(IUserService userService)
        {
            this.userService = userService;
      
        }

        public IActionResult Index(decimal totalValue)
        {
            ViewBag.TotalValue = totalValue;
            return View();
        }
    }
}

bookStoreTurkcell/Views/Cart/Index.cshtml
@model Cart
@{
    ViewData["Title"] = "Index";
    decimal totalValue = Model.GetTotalValue();
    string totVal = Convert.ToDecimal(totalValue).ToString("###0,00");

}

<h1>Sepetim</h1>
<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th>Kitabın Adı</th>
            <th>Kitabın Fiyatı</th>
            <th>Adet</th>
            <th>Ara Toplam</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.CartLines)
        {
            <tr>
                <td>@item.Book.Name</td>
                <td>@(item.Book.Price * (decimal)(1- item.Book.Discount))</td>
                <td>@item.Quantity</td>
                <td>@((item.Book.Price * (decimal)(1 - item.Book.Discount))* item.Quantity)</td>
                <td>
                    <a asp-action="Delete" asp-controller="Cart" asp-route-ID="@item.Book.ID" class="btn btn-danger"> Sil </a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3"> Toplam Fiyat: </td>
            <td>@Model.GetTotalValue() TL</td>
        </tr>
    </tfoot>
</table>
@if (Model.GetTotalValue() >= 100)
{
    <div class="alert alert-success" role="alert">
        Tebrikler, 100₺ ve üstünde kargo bedava!
    </div>
}
<a class="btn btn-lg btn-info" href="@ViewBag.ReturnURL">Alışverişe Devam Et</a>
<a class="btn btn-lg btn-dark" asp-action="Index" asp-controller="Order" asp-route-totalValue = "@totVal">Siparişi Tamamla</a>